" Filetype plugin tells matchit about pairs and probably more.
" This didn't work until I moved it before Pathogen.
filetype on
filetype indent on
filetype plugin on

" Start pathogen for managing plugins, etc.
call pathogen#infect()

" Powerline
set encoding=utf-8
set guifont=Monaco-Powerline
let g:Powerline_symbols = 'fancy'

" New vim
set nocompatible

" Allow hiding edited bufferes
set hidden

"" Tabs and indenting
set bs=2
set tabstop=2
set shiftwidth=2
set expandtab
set autoindent

" Don't automatically insert linebreaks in long lines
set wrap linebreak textwidth=0

" Don't automatically show long lines wrapped
set nowrap

" Show line numbers
set number
set hlsearch

" Show $ at end of thing being changed
set cpoptions+=$

" Show status line even if single window
set laststatus=2

" Syntax highlighting
syntax enable

" Color scheme
set background=dark
colorscheme base16-eighties

" Misc
set wildmode=longest,list,full
set wildmenu

" Custom filetype, syntax mappings
au BufRead,BufNewFile *.rep setfiletype rep syntax=ruby
au BufRead,BufNewFile *.json setfiletype json syntax=javascript
autocmd Filetype js set textwidth=80

" Mouse support
set mouse=a
set ttymouse=xterm2   " Allows mouse dragging

" Term settings
set term=xterm-256color

" System clipboard sharing
set clipboard=unnamed

" Show the filename in the window titlebar
set title

" Leader and friends
map , \

" Reselect visual area when changing indent in visual mode (from @notahat)
vnoremap < <gv
vnoremap > >gv

" AUTOMATIC SAVING
au FocusLost * silent! wa   " FocusLost only works in GUI vim (and for CTRL-Z)
" au WinLeave,TabLeave * silent! wa
" set autowriteall   " on buffer switch

" NERDTree settings
let NERDTreeWinSize=35
silent! map <F3> :NERDTreeFind<cr>
let g:NERDTreeMapActivateNode="<F3>"
let g:NERDTreeMapPreview="<F4>"

" Highligh trailing white spaces on non-insert mode
highlight ExtraWhitespace ctermbg=red guibg=red
au ColorScheme * highlight ExtraWhitespace guibg=red
au BufEnter * match ExtraWhitespace /\s\+$/
au InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
au InsertLeave * match ExtraWhiteSpace /\s\+$/

" Strip trailing whitespace (,ss)
noremap <F2> :set et<CR>:retab!<CR>:%s/[\r \t]\+$//<CR>

" Generate tags on current folder
map <F8> :!/usr/local/bin/ctags -R --c++-kinds=+p --fields=+iaS --extra=+q .<CR>
nnoremap <c-]> g<c-]>
vnoremap <c-]> g<c-]>
